Repository mattbrictson/tomo, pull requests merged in 2019-08, with the labels that each got.

#36 Fix unknown deploy user on when deploying via Circle CI
  docs/plugins/core.md
  lib/tomo/plugin/core.rb
  lib/tomo/plugin/git/tasks.rb
  lib/tomo/runtime.rb
  test/tomo/runtime_test.rb
Labels: 🐛 Bug Fix

#37 Add tutorial for deploying Rails via tomo
  README.md
  docs/css/extra.css
  docs/tutorials/deploying-rails-from-scratch.md
  docs/tutorials/ssh-auth@2x.png
  docs/tutorials/ubuntu-18-lts@2x.png
  test/rails_setup_deploy_e2e_test.rb
Labels: 📚 Docs

#38 Migrate to new GitHub Actions config format
  .github/main.workflow
  .github/workflows/push.yml
Labels: 🏠 Housekeeping

#39 Fix hang when starting puma 4.1.0
  docs/plugins/puma.md
  lib/tomo/plugin/puma.rb
  lib/tomo/plugin/puma/tasks.rb
  test/tomo/plugin/puma/tasks_test.rb
Labels: 🐛 Bug Fix

#40 Link directories needed by puma (Rails 6 support)
  lib/tomo/templates/config.rb.erb
Labels: ✨ Feature

#41 Enable RAILS_SERVE_STATIC_FILES by default
  lib/tomo/templates/config.rb.erb
Labels: ✨ Feature

#42 Document the env:show task
  docs/plugins/env.md
Labels: 📚 Docs

#29 Replace nvm with nodenv
  README.md
  docs/commands/init.md
  docs/commands/setup.md
  docs/commands/tasks.md
  docs/configuration.md
  docs/plugins/nodenv.md
  docs/plugins/nvm.md
  lib/tomo/plugin/nodenv.rb
  lib/tomo/plugin/nodenv/tasks.rb
  lib/tomo/plugin/nvm.rb
  lib/tomo/plugin/nvm/tasks.rb
  lib/tomo/templates/config.rb.erb
  mkdocs.yml
  test/rails_setup_deploy_e2e_test.rb
Labels: ⚠️ Breaking

#43 Add unit tests for nodenv plugin
  test/tomo/plugin/nodenv/tasks_test.rb
Labels: 🏠 Housekeeping

#44 Bump Ruby versions used for CI
  .circleci/Dockerfile
  .circleci/config.yml
  .travis.yml
Labels: 🏠 Housekeeping

#45 Handle nil path settings more consistently
  lib/tomo/paths.rb
  test/tomo/paths_test.rb
Labels: 🐛 Bug Fix
