Repository mattbrictson/tomo, pull requests merged in 2020-01, with the labels that each got.

#94 Allow puma listen address to be changed from default 0.0.0.0
  docs/plugins/puma.md
  lib/tomo/plugin/puma.rb
  lib/tomo/plugin/puma/systemd/service.erb
  lib/tomo/plugin/puma/systemd/socket.erb
Labels: ✨ Feature

#96 Upgrade CI to Bundler 2.1.3
  .circleci/Dockerfile
  .circleci/config.yml
  .travis.yml
Labels: 🏠 Housekeeping

#97 Improve console detection; treat CI as non-interactive
  lib/tomo/console.rb
  lib/tomo/console/key_reader.rb
  lib/tomo/console/menu.rb
  test/tomo/console_test.rb
Labels: ✨ Feature

#98 Remove unused require statement
  lib/tomo/task_library.rb
Labels: 🏠 Housekeeping

#100 Upgrade CI to Bundler 2.1.4
  .circleci/Dockerfile
  .circleci/config.yml
  .travis.yml
Labels: 🏠 Housekeeping

#101 Improve env:update output and error handling
  lib/tomo/console.rb
  lib/tomo/console/non_interactive_error.rb
  lib/tomo/plugin/env/tasks.rb
Labels: ✨ Feature

#102 Update plugin tutorial to match latest template
  docs/tutorials/publishing-a-plugin.md
Labels: 📚 Docs
