Repository mattbrictson/tomo, pull requests merged in 2020-04, with the labels that each got.

#114 Upgrade CI to use latest Ruby security releases
  .circleci/Dockerfile
  .circleci/config.yml
  .travis.yml
Labels: 🏠 Housekeeping

#115 Fail loudly if tomo cannot guess bundler version
  docs/plugins/bundler.md
  lib/tomo/plugin/bundler/tasks.rb
  test/tomo/plugin/bundler/tasks_test.rb
Labels: ⚠️ Breaking

#117 Drop support for Ruby 2.4 (EOL)
  .rubocop.yml
  .travis.yml
  docs/comparisons.md
  lib/tomo/runtime/settings_interpolation.rb
  lib/tomo/runtime/task_runner.rb
  lib/tomo/ssh/child_process.rb
  tomo.gemspec
Labels: ⚠️ Breaking

#116 Update version numbers referenced in docs to 1.0.0
  docs/api/Logger.md
  docs/commands/deploy.md
  docs/commands/setup.md
  docs/plugins/env.md
  docs/tutorials/deploying-rails-from-scratch.md
  docs/tutorials/writing-custom-tasks.md
  readme_images/tomo-run-hello.png
  readme_images/tomo-run-rails-console.png
Labels: 📚 Docs

#119 CI: Drop unused Travis sudo: false directive
  .travis.yml
Labels: 🏠 Housekeeping

#121 Upgrade Ubuntu image used for testing to 20.04 LTS
  docs/api/testing/DockerPluginTester.md
  lib/tomo/testing/Dockerfile
  lib/tomo/testing/docker_image.rb
Labels: 🏠 Housekeeping

#123 Ensure puma starts eagerly on system boot
  lib/tomo/plugin/puma/systemd/service.erb
Labels: ✨ Feature

#124 Update Rails tutorial to use Ubuntu 20.04 LTS
  docs/css/extra.css
  docs/tutorials/deploying-rails-from-scratch.md
  docs/tutorials/ubuntu-18-lts@2x.png
  docs/tutorials/ubuntu-20-lts@2x.png
Labels: 📚 Docs
