Repository mattbrictson/tomo, pull requests merged in 2020-10, with the labels that each got.

#183 Upgrade CI to Ruby 2.7.2
  .circleci/Dockerfile
  .circleci/config.yml
Labels: automerge, 🏠 Housekeeping

#184 Explicitly tag image to fix test failures with new Docker version
  lib/tomo/testing/docker_image.rb
Labels: automerge, 🏠 Housekeeping

#185 Clean up README and comparisons document
  README.md
  docs/comparisons.md
Labels: automerge, 📚 Docs

#187 Autodetect rbenv_ruby_version via .ruby-version file
  docs/plugins/rbenv.md
  lib/tomo/plugin/rbenv/tasks.rb
  lib/tomo/templates/config.rb.erb
Labels: automerge, ✨ Feature

#188 Generate config.rb with explicit Ruby version, if needed
  lib/tomo/commands/init.rb
  lib/tomo/templates/config.rb.erb
Labels: automerge, ✨ Feature

#189 Add test coverage for rbenv:install task
  test/tomo/plugin/rbenv/tasks_test.rb
Labels: automerge, 🏠 Housekeeping

#190 Fix broken "edit on GitHub" links
  mkdocs.yml
Labels: automerge, 📚 Docs
