Repository mattbrictson/tomo, pull requests merged in 2023-01, with the labels that each got.

#350 Enable Ruby 3.2's YJIT by default for new projects
  docs/tutorials/deploying-rails-from-scratch.md
  lib/tomo/templates/config.rb.erb
  lib/tomo/testing/ubuntu_setup.sh
Labels: ✨ Feature, automerge

#351 Show verbose output when compiling Ruby
  lib/tomo/plugin/rbenv/tasks.rb
  test/tomo/plugin/rbenv/tasks_test.rb
Labels: ✨ Feature, automerge

#352 Fix typo in test method name
  test/tomo/plugin/puma/tasks_test.rb
Labels: 🏠 Housekeeping, automerge

#353 Replace Circle CI with Semaphore CI
  .circleci/Dockerfile
  .circleci/config.yml
  .semaphore/deploy-docs.yml
  .semaphore/semaphore.yml
  README.md
  Rakefile
  docs/comparisons.md
  test/support/ci.rb
  test/support/circleci.rb
Labels: 🏠 Housekeeping

#356 Use proper branch name for PR workflows in CI
  .semaphore/semaphore.yml
Labels: 🏠 Housekeeping, automerge

#357 Remove docker complexity no longer needed by CI
  lib/tomo/testing/docker_image.rb
  lib/tomo/testing/local.rb
Labels: 🏠 Housekeeping, automerge

#359 Recommend 1GB minimum droplet RAM
  .gitignore
  docs/css/extra.css
  docs/tutorials/deploying-rails-from-scratch.md
  docs/tutorials/smallest-viable-droplet@2x.png
Labels: automerge

#360 Enable rubocop for ruby snippets in .md files
  .rubocop.yml
  Gemfile
Labels: 🏠 Housekeeping, automerge
